#!/bin/sh

home_path=${HOME}

. $home_path/etc/conf/bashrc

echo "source"

\rm -rf $home_path/.vimrc
\rm -rf $home_path/.vimrc.bundles
\rm -rf $home_path/.vimrc.local
\rm -rf $home_path/.bashrc
\rm -rf $home_path/.tmux.conf
\rm -rf $home_path/.machine
\rm -rf $home_path/.go
\rm -rf $home_path/.vim/bundle/Vundle.vim

# vim
ln -s $home_path/etc/conf/vimrc $home_path/.vimrc
ln -s $home_path/etc/conf/vimrc.bundles $home_path/.vimrc.bundles
ln -s $home_path/etc/conf/vimrc.local $home_path/.vimrc.local

# bash
ln -s $home_path/etc/conf/bashrc $home_path/.bashrc
ln -s $home_path/etc/conf/tmux.conf $home_path/.tmux.conf
ln -s $home_path/etc/conf/machine $home_path/.machine
ln -s $home_path/etc/bin/go $home_path/.go

# mkdir
mkdir -p $home_path/.vim/backup
mkdir -p $home_path/.vim/bundle
mkdir -p $home_path/.trash

cd $home_path

git clone https://github.com/VundleVim/Vundle.vim.git $home_path/.vim/bundle/Vundle.vim
