#!/bin/sh

\rm -rf ~/.vimrc
\rm -rf ~/.vimrc.bundles
\rm -rf ~/.vimrc.local
\rm -rf ~/.bashrc
\rm -rf ~/.tmux.conf
\rm -rf ~/.machine
\rm -rf ~/.go

ln -s ~/etc/vimrc ~/.vimrc
ln -s ~/etc/vimrc.bundles ~/.vimrc.bundles
ln -s ~/etc/vimrc.local ~/.vimrc.local
ln -s ~/etc/bashrc ~/.bashrc
ln -s ~/etc/tmux.conf ~/.tmux.conf
ln -s ~/etc/machine ~/.machine
ln -s ~/etc/go ~/.go

mkdir -p ~/.vim/backup
mkdir -p ~/.trash
mkdir -p ~/.vim/bundle

cd ~
source .bashrc

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle
